# Generated by Django 4.0.2 on 2022-03-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='book',
            name='edition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/books/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/series/'),
        ),
    ]
