# Generated by Django 6.0.2 on 2026-02-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="images/books/"),
        ),
        migrations.AlterField(
            model_name="series",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="images/series/"),
        ),
    ]
